import type { Trigger } from "@src/shared/triggers"

export const triggerEvents: { value: Trigger["event"]; label: string; actions: string[] }[] = [
  { value: "issues", label: "Issue", actions: ["opened", "edited", "closed", "reopened", "labeled", "unlabeled", "assigned", "unassigned", "locked", "unlocked", "deleted", "transferred", "milestoned", "demilestoned", "pinned", "unpinned"] },
  { value: "issue_comment", label: "Comentário em issue ou PR", actions: ["created", "edited", "deleted"] },
  { value: "pull_request", label: "Pull request", actions: ["opened", "edited", "closed", "reopened", "synchronize", "ready_for_review", "converted_to_draft", "labeled", "unlabeled", "assigned", "unassigned", "review_requested", "review_request_removed", "locked", "unlocked", "auto_merge_enabled", "auto_merge_disabled", "milestoned", "demilestoned", "enqueued", "dequeued"] },
  { value: "pull_request_review", label: "Revisão de pull request", actions: ["submitted", "edited", "dismissed"] },
  { value: "pull_request_review_comment", label: "Comentário em revisão", actions: ["created", "edited", "deleted"] },
  { value: "check_run", label: "Check", actions: ["created", "completed", "rerequested", "requested_action"] },
]

export const triggerActionLabels: Record<string, string> = {
  opened: "Abertura",
  edited: "Edição",
  closed: "Fechamento",
  reopened: "Reabertura",
  labeled: "Label adicionada",
  unlabeled: "Label removida",
  assigned: "Responsável adicionado",
  unassigned: "Responsável removido",
  locked: "Conversa bloqueada",
  unlocked: "Conversa desbloqueada",
  deleted: "Remoção",
  transferred: "Transferência",
  milestoned: "Marco adicionado",
  demilestoned: "Marco removido",
  pinned: "Fixação",
  unpinned: "Desafixação",
  created: "Criação",
  synchronize: "Novos commits",
  ready_for_review: "Pronto para revisão",
  converted_to_draft: "Convertido em rascunho",
  review_requested: "Revisão solicitada",
  review_request_removed: "Solicitação de revisão removida",
  auto_merge_enabled: "Merge automático ativado",
  auto_merge_disabled: "Merge automático desativado",
  enqueued: "Entrada na fila de merge",
  dequeued: "Saída da fila de merge",
  submitted: "Envio",
  dismissed: "Revisão dispensada",
  completed: "Conclusão",
  rerequested: "Solicitado novamente",
  requested_action: "Ação solicitada",
}
